services:
  - type: web
    name: insurance-whatsapp-bot
    env: node
    buildCommand: |
      npm install
      cp marketing_templates.json /opt/render/project/
    startCommand: node index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: TWILIO_ACCOUNT_SID
        sync: false
      - key: TWILIO_AUTH_TOKEN
        sync: false
      - key: TWILIO_PHONE_NUMBER
        sync: false
      - key: WHATSAPP_PHONE_NUMBER
        sync: false 