services:
  - type: web
    name: admon-agent           # leave as-is or adjust to your Render name
    env: node

    # ---------- Build step ----------
    buildCommand: |
      npm ci
      npm run seed:embeddings

    # ---------- Start step ----------
    startCommand: node index.js 